apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
metadata:
  name: terminal-kanban
build:
  local:
    push: false
  artifacts:
    - image: abilityjlr/tui
      context: tui
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "cmd/**/*.go"
            dest: .

